#!/usr/bin/env python3
"""
prepare_mmpbsa.py
=================
Turn the pipeline's Amber export + trajectory into a ready-to-run (or
already-run) single-trajectory MM/PB(GB)SA calculation with AmberTools.

`export_amber.py` writes the topologies; this script closes the last two gaps:

  1. Builds the **dry, pbc-removed trajectory** (protein + ligand only,
     superposed on the protein) whose atom order matches `*_complex_dry.prmtop`.
  2. Writes `mmpbsa.in` and a `run_mmpbsa.sh` that splits receptor/ligand with
     `ante-MMPBSA.py` and runs `MMPBSA.py`.  If those AmberTools binaries are on
     PATH (e.g. an env that has `ambertools`), it runs them here and parses the
     resulting ΔG; otherwise it just emits the script to run in your AmberTools
     env (`export AMBERHOME=<env>` first).

The MD/parameterization env usually does NOT contain AmberTools, so `run="auto"`
(the default) runs only when the tools are actually available.
"""

import argparse
import json
import logging
import os
import re
import shutil
import subprocess
import textwrap

# same water/ion residue names export_amber strips for the dry complex
WATER_IONS = "WAT,HOH,SOL,Na+,Cl-,K+,NA,CL,K,MG,ZN,Mg2+,Zn2+"


def _build_dry_traj(trajectory, topology, resnames, align_selection, out_dcd):
    """Write a dry (protein+ligand), protein-superposed DCD; return n_atoms/n_frames."""
    import mdtraj as md

    traj = md.load(trajectory, top=topology)
    keep = f"protein or resname {' '.join(resnames)}" if resnames else "protein"
    dry = traj.atom_slice(traj.top.select(keep))
    align_idx = dry.top.select(align_selection)
    if len(align_idx):
        dry.superpose(dry, 0, atom_indices=align_idx)
    dry.save_dcd(out_dcd)
    return dry.n_atoms, dry.n_frames


def _prmtop_natoms(prmtop):
    try:
        import parmed
        return len(parmed.load_file(prmtop).atoms)
    except Exception:
        return None


def main(trajectory, topology, dry_prmtop, output_dir, ligand_resnames,
         align_selection="protein and name CA", igb=5, saltcon=0.15,
         startframe=1, interval=1, run="auto", json_output=None):
    os.makedirs(output_dir, exist_ok=True)
    resnames = sorted(set(ligand_resnames or []))
    dry_dcd = os.path.join(output_dir, "dry.dcd")

    n_atoms, n_frames = _build_dry_traj(trajectory, topology, resnames, align_selection, dry_dcd)
    print(f"Dry trajectory: {n_atoms} atoms, {n_frames} frames -> {dry_dcd}")

    expected = _prmtop_natoms(dry_prmtop)
    if expected is not None and expected != n_atoms:
        print(f"WARNING: dry.dcd has {n_atoms} atoms but {dry_prmtop} has {expected}. "
              f"Check that --ligand_resnames matches the export.")

    ligand_mask = ":" + ",".join(resnames) if resnames else ":LIG"
    strip_mask = ":" + WATER_IONS

    # mmpbsa.in
    mmpbsa_in = os.path.join(output_dir, "mmpbsa.in")
    with open(mmpbsa_in, "w") as f:
        f.write(textwrap.dedent(f"""\
            Single-trajectory MM-GBSA generated by prepare_mmpbsa.py
            &general
              startframe={startframe}, endframe={n_frames}, interval={interval}, verbose=2,
            /
            &gb
              igb={igb}, saltcon={saltcon},
            /
            """))

    # run_mmpbsa.sh (absolute prmtop path so it works from anywhere)
    abs_prmtop = os.path.abspath(dry_prmtop)
    run_sh = os.path.join(output_dir, "run_mmpbsa.sh")
    with open(run_sh, "w") as f:
        f.write(textwrap.dedent(f"""\
            #!/usr/bin/env bash
            # Run in an env that has AmberTools (MMPBSA.py / ante-MMPBSA.py):
            #   export AMBERHOME=/path/to/your/ambertools/env   # e.g. a conda env prefix
            #   bash run_mmpbsa.sh
            set -euo pipefail
            cd "$(dirname "$0")"
            : "${{AMBERHOME:?set AMBERHOME to your AmberTools env prefix}}"
            ante-MMPBSA.py -p "{abs_prmtop}" -c com.prmtop -r rec.prmtop -l lig.prmtop \\
                -s '{strip_mask}' -n '{ligand_mask}'
            MMPBSA.py -O -i mmpbsa.in -cp "{abs_prmtop}" -rp rec.prmtop -lp lig.prmtop \\
                -y dry.dcd -o FINAL_RESULTS.dat -eo FINAL_RESULTS.csv
            """))
    os.chmod(run_sh, 0o755)
    print(f"Wrote {mmpbsa_in} and {run_sh}")

    result = {
        "step": "prepare_mmpbsa",
        "status": "prepared",
        "dry_trajectory": dry_dcd,
        "dry_prmtop": abs_prmtop,
        "mmpbsa_in": mmpbsa_in,
        "run_script": run_sh,
        "ligand_mask": ligand_mask,
        "n_frames": n_frames,
        "delta_total_kcal_mol": None,
    }

    ante = shutil.which("ante-MMPBSA.py")
    mmpbsa = shutil.which("MMPBSA.py")
    should_run = run == "yes" or (run == "auto" and ante and mmpbsa)
    if run == "yes" and not (ante and mmpbsa):
        raise RuntimeError("run='yes' but ante-MMPBSA.py / MMPBSA.py are not on PATH. "
                           "Activate your AmberTools env or use run='auto'/'no'.")

    if should_run:
        print("AmberTools found on PATH -> running MM-GBSA now...")
        env = dict(os.environ)
        env.setdefault("AMBERHOME", os.path.dirname(os.path.dirname(mmpbsa)))
        subprocess.run(["bash", os.path.basename(run_sh)], cwd=output_dir, env=env, check=True)
        dat = os.path.join(output_dir, "FINAL_RESULTS.dat")
        result.update(status="completed", results_dat=dat,
                      results_csv=os.path.join(output_dir, "FINAL_RESULTS.csv"),
                      delta_total_kcal_mol=_parse_delta_total(dat))
        print(f"MM-GBSA ΔTOTAL = {result['delta_total_kcal_mol']} kcal/mol")
    else:
        print("AmberTools not on PATH -> wrote run_mmpbsa.sh to run in your AmberTools env "
              "(set AMBERHOME, then `bash run_mmpbsa.sh`).")

    if json_output:
        with open(json_output, "w") as f:
            json.dump(result, f, indent=2)
    return result


def _parse_delta_total(dat_path):
    try:
        txt = open(dat_path).read().split("Differences (Complex - Receptor - Ligand):")[-1]
        m = re.search(r"^DELTA TOTAL\s+(-?\d+\.\d+)", txt, re.MULTILINE)
        return float(m.group(1)) if m else None
    except Exception:
        return None


if __name__ == "__main__":
    logging.basicConfig(
        level=getattr(logging, os.environ.get("LIGAND_LOG_LEVEL", "INFO").upper(), logging.INFO),
        format="%(asctime)s | %(levelname)-7s | %(name)s | %(message)s",
        datefmt="%H:%M:%S", force=True,
    )
    p = argparse.ArgumentParser(
        description="Build the dry trajectory + inputs and (optionally) run AmberTools MM/PB(GB)SA.")
    p.add_argument("-t", "--trajectory", required=True, help="Unwrapped trajectory (production/unwrapped .dcd)")
    p.add_argument("-to", "--topology", required=True, help="Matching topology PDB (unwrapped_topology.pdb)")
    p.add_argument("-p", "--dry_prmtop", required=True, help="*_complex_dry.prmtop from export_amber.py")
    p.add_argument("-o", "--output_dir", required=True, help="Directory for dry.dcd / mmpbsa.in / results")
    p.add_argument("--ligand_resnames", nargs="+", required=True, help="Ligand residue name(s), e.g. LIG")
    p.add_argument("--align_selection", default="protein and name CA")
    p.add_argument("--igb", type=int, default=5)
    p.add_argument("--saltcon", type=float, default=0.15)
    p.add_argument("--startframe", type=int, default=1)
    p.add_argument("--interval", type=int, default=1)
    p.add_argument("--run", choices=["auto", "yes", "no"], default="auto",
                   help="auto: run if AmberTools on PATH; yes: require+run; no: only write files")
    p.add_argument("--json", dest="json_output", default=None)
    args = p.parse_args()
    main(args.trajectory, args.topology, args.dry_prmtop, args.output_dir,
         args.ligand_resnames, args.align_selection, args.igb, args.saltcon,
         args.startframe, args.interval, args.run, args.json_output)
